### ISSUE TITLE
I want Plugin URIs to be clearly defined, not arbitrarily

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1087]
# Motivation
Currently, plugin URIs are defined in a arbitrary way, which can easily break composability as the Polywrap development ecosystem grows and decentralizes. We should have tailored developer experience that ensure plugin URIs are not arbitrary, and are defined in clearly understandable ways.

# Sub-Stories & Sub-Tasks
- [x] As a plugin developer, I want to implement an interface (new or existing)
  - [x] Link plugin projects to an external interface
  - [x] Link plugin projects to a local interface
- [x] As a wrapper developer, I want to depend on plugins in a transparent way
  - [x] Wrapper developers are able to import & invoke plugins given their interface's URI
  - [x] Wrapper developers are able to import & invoke plugins given their pre-bundled `wrap.info`

**Comment by dOrgJelli** [comment]
@polywrap/dev feedback requested

**Comment by nerfZael** [comment]
LGTM
