### ISSUE TITLE
uts46, sha3, and subgraph plugins are wrappers and are no longer in the default plugins

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1124]
The uts46, sha3, and subgraph plugins can be replaced with Rust wrappers. Each of these plugins can be removed from default plugins once it has a working wrapper. The packages in  the [demos](https://github.com/polywrap/demos) or [integrations](https://github.com/polywrap/integrations) repos should not be affected by this change since plugins and wasm wrappers are generally interchangeable, but it's important to make sure no packages are broken by side affects.

- [x] uts46 wrapper completed https://github.com/polywrap/integrations/issues/102
- [x] sha3 wrapper completed https://github.com/polywrap/integrations/issues/103
- [x] subgraph wrapper completed https://github.com/polywrap/integrations/issues/104
- [x] uts64, sha3, and subgraph plugins are no longer in the default plugins https://github.com/polywrap/monorepo/issues/1125
- [x] packages in demos and integrations repos are not broken by this change
