### ISSUE TITLE
Make the Serde dependency optional in Rust wrappers

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1178]
**Is your feature request related to a problem? Please describe.**
Rust wrappers are nearly twice the size of AssemblyScript wrappers

**Describe the solution you'd like**
Make the Serde package (crate) optional. 

See Jordan's comment below for context:
- [ ] Add codegen manifest https://github.com/polywrap/toolchain/issues/1278
- [ ] Add codegen manifest extensions for binding targets https://github.com/polywrap/toolchain/issues/1279
- [ ] Add option to enable or disable serde in Rust codegen manifest https://github.com/polywrap/toolchain/issues/1280

**Additional context**
- allow user to change generated code by giving option to not run codegen while building https://github.com/polywrap/toolchain/issues/796
- Improved JSON Serialization Bindings For AssemblyScript https://github.com/polywrap/toolchain/issues/633

**Comment by dOrgJelli** [comment]
@krisbitney a few quick thoughts.

1. It feels weird to have language-specific annotations within the schema. In my mind, the schema should be "portable" to multiple implementation languages. I understand that the schema is just used at development-time, and what it gets built to is the ABI, but it still feels a bit... odd.
2. I was thinking there could be an easy way in Rust to add traits to a pre-defined struct, maybe by inheriting & adding the serde attributes, but Rust doesn't support inheritance. Instead the developer would have to compose them like so:
```rust
struct BaseNonSerde {
  prop: u8;
}

#[derive(Serialize, Deserialize)]
struct EnableSerde {
  base: BaseNonSerde;
}
```
This is pretty poor UX though...
3. It seems to me that we want the ability to configure the codegen / schema binding process. Why not use the same developer experience we implemented for different build images (see [here](https://github.com/polywrap/toolchain/blob/origin/packages/cli/src/lib/defaults/build-images/wasm/assemblyscript/polywrap.build.ext.json))?

The solution would go like this:
- We would make a new Polywrap manifest for the codegen process (we've been talking about this for a while). Call it `polywrap.codegen.yaml`.
- Each binding language (`wasm/rust`, `wasm/assemblyscript`, `plugin/typescript`, etc) can now define its own manifest extension schema for `polywrap.codegen.yaml`, just like the `polywrap.build.ext.json` file linked above.
- Within these manifest extensions, we can add custom configuration properties for things like `enable_serde`. This property could be of type `boolean | string[]`, so that users can enable for all types, or specify an array of type names to enable them for. NOTE: we may want something more specific than just an array of strings, maybe `{ objects: boolean | string[]; methods: boolean | string[]; etc }`
- These custom configuration properties would be passed into the bindings, which would them modify what code is generated based on them.

**Comment by krisbitney** [comment]
Closing since serde is already successfully removed by wasm-snip
