### ISSUE TITLE
I want to build & deploy a JS wrapper

### ISSUE THREAD

**Issue by blubber-fish** [Web3-API/prototype#1401]
Sub-Tasks:

- [ ] [Define the developer experience](https://github.com/polywrap/toolchain/issues/1402)
- [ ] [Bind schema to JS wrapper](https://github.com/polywrap/toolchain/issues/1403)
- [ ] [Build JS wrapper](https://github.com/polywrap/toolchain/issues/1404)
- [ ] [Define a runtime to be used](https://github.com/polywrap/toolchain/issues/1405)

**Comment by blubber-fish** [comment]
~ Comment moved by @dOrgJelli ~
