### ISSUE TITLE
I want to read quality, detailed, and up-to-date docs for every wrapper

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#702]
At minimum, Polywrap users need to know a wrapper's interface to make queries. But often users will need more information, as they do with any SDK. We should make it easy for wrapper developers to create documentation for their projects, and make it easy for dApp developers to find that documentation. 

It would also be useful to provide dApp developers a way to learn a wrapper's interface even when the wrapper developer didn't write anything. This could be done by querying a uri with a CLI tool, or perhaps by using a search tool on our website that accepts a uri and returns the wrapper's schema.

The solutions to these tasks should also support plugins.

- [x] As a wrapper developer, there are tools to help me create quality documentation for my wrapper. See issue: https://github.com/polywrap/monorepo/issues/4
- [x] As a dApp developer, it is easy to find documentation produced by wrapper developers. See Hub issue: https://github.com/polywrap/hub/issues/179
- [x] As a dApp developer, I can obtain a wrapper's interface in a presentable format even when the wrapper developers did not write or publish any documentation. See issue: https://github.com/polywrap/monorepo/issues/4

**Comment by dOrgJelli** [comment]
I think we should add an issue to The Hub for this. It'd be great to foward users to the hub where they can read through the schema & see documentation in an easy user-friendly way.

**Comment by evanjacobs** [comment]
Perhaps we can scope this down to having good documentation for the wrappers that are used in integrations.

Remaining steps:
1. Merge PR for #4 
2. Generate docs and add them to integrations repo
3. Links from docs to integrations and vice versa

**Comment by dOrgJelli** [comment]
@krisbitney @Niraj-Kamdar now that the docgen command is complete, I think we should setup a new documentation website hosted at `integrations.polywrap.io`.

The website's source code can be within the https://github.com/polywrap/integrations repo, within a `docs/` folder.

It can have an automated build process setup where it:
- iterates through all integrations (system/filesystem, protocol/ethereum/ens, etc)
- runs `polywrap docgen` and outputs them to their respective folders within the `docs/...` directory

This way, we have an auto-updating documentation website for all integrations that we add to the integrations repo.

Thoughts?

**Comment by krisbitney** [comment]
> @krisbitney @Niraj-Kamdar now that the docgen command is complete, I think we should setup a new documentation website hosted at `integrations.polywrap.io`.
> 
> The website's source code can be within the https://github.com/polywrap/integrations repo, within a `docs/` folder.
> 
> It can have an automated build process setup where it:
> 
> * iterates through all integrations (system/filesystem, protocol/ethereum/ens, etc)
> * runs `polywrap docgen` and outputs them to their respective folders within the `docs/...` directory
> 
> This way, we have an auto-updating documentation website for all integrations that we add to the integrations repo.
> 
> Thoughts?

This is a great idea. It should be easy to set up. I'll try to get this set up tonight.

**Comment by krisbitney** [comment]
@krisbitney @Niraj-Kamdar PR up here https://github.com/polywrap/integrations/pull/100. Feedback welcome!
